### ISSUE TITLE
Settlement Day + Settlement Period  = datetime_utc

### ISSUE THREAD

**Issue by peterdudfield** [OSUKED/NGDataPortal#6]
Would it be possible to add function that changes the settlement day and settlement period to a datetime_utc. Then we dont get into any messy situations with clocks changes e.t.c. 

I'm happy to give it a go first

**Comment by AyrtonB** [comment]
Yes that would be very welcome, there's some related code in the ElexonDataPortal library as well. Thank you!

**Comment by AyrtonB** [comment]
Closed with https://github.com/OSUKED/NGDataPortal/pull/7
